// <auto-generated />
namespace AgendaIN6AV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_AGENDA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_AGENDA));
        
        string IMigrationMetadata.Id
        {
            get { return "201603270316068_DB_AGENDA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
